services:
  db:
    image: postgres:16
    container_name: crypto_postgres

    environment:
      POSTGRES_USER: hagen
      POSTGRES_PASSWORD: Cookie2309
      POSTGRES_DB: crypto_db

    ports:
      - "5433:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: